apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: ansible-project-template
  title: Ansible Automation Platform Project Template
  description: Define a new Ansible Project
  tags:
    - recommended
    - aap
spec:
  owner: cooktheryan
  type: service
  parameters:
    - title: Provide information about the GitHub location
      required:
        - githubOrg
        - repo_name
      properties:
        owner:
          title: Owner
          type: string
          description: Owner of the component
          default: 'user: cooktheryan'
        repo_name:
          title: Repository Name
          type: string
          default: 'backstage-awx-resources'
        githubOrg:
          title: GitHub Organization
          type: string
          default: 'cooktheryan'
        repoName:
          title: Repository Name
          type: string
          default: 'backstage-awx-resources'
    - title: AAP Project Defintion
      required:
        - description
        - name
        - codeRepo
        - scm_type
        - organization
      properties:
        name:
          title: Name of the project
          type: string
          description: The name of the project
        description:
          title: Description
          type: string
          description: Description of the project
        scm_type:
          title: SCM for the project Assets
          type: string
          default: Git
          enum:
            - git
            - archive
          enumNames:
            - Git
            - Zip File
        repo:
          title: URL
          type: string
          description: The URL for the Git repository or archive
        organization:
          title: Organization
          type: string
          default: Default
          description: The organization for the project
  steps:
    - id: template
      name: Generating the source code component
      action: fetch:template
      input:
        url: ./skeleton
        targetPath: projects
        values:
          component_id: ${{ parameters.name }}
          repo: ${{ parameters.codeRepo }}
          branch: ${{ parameters.branch }}
          name: ${{ parameters.name }}
          scm_type: ${{ parameters.scm_type }}
          organization: ${{ parameters.organization }}}
          description: ${{ parameters.description }}

    - id: catalog-template
      name: Generating catalog-info.yaml
      action: fetch:template
      input:
        url: ../../scaffolder-skeletons/catalog-info-skeleton/
        values:
          github_org: ${{ parameters.githubOrg }}
          repo_name: ${{ parameters.repo_name }}
          description: ${{ parameters.description }}
          owner: ${{ parameters.owner}}

    - id: publish
      name: Publishing to Source Code Repository
      action: publish:github:pull-request
      input:
        allowedHosts: ['github.com']
        title: ${{ parameters.name }}-project
        description: ${{ parameters.description }}
        repoUrl: github.com?owner=${{ parameters.githubOrg }}&repo=${{ parameters.repoName }}
        branchName: ${{ parameters.name }}-project

    - id: register
      name: Registering the component
      action: catalog:register
      input:
        repoContentsUrl: https://github.com/${{ parameters.githubOrg }}/${{ parameters.repo_name }}/tree/${{ parameters.name }}-schedule/schedules
        catalogInfoPath: '/catalog-info.yaml'

  output:
    links:
      - title: Source Code Repository
        url: ${{ steps.publish.output.remoteUrl }}
      - title: Open Component in catalog
        icon: catalog
        entityRef: ${{ steps.register.output.entityRef }}
