apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: ansible-project-template
  title: AAP Project Template
  description: Define a new Ansible Project
  tags:
    - recommended
    - aap
spec:
  owner: cooktheryan
  type: service

  parameters:
    - title: Provide information about the GitHub location
      required:
        - githubOrg
        - repoName
      properties:
        githubOrg:
          title: GitHub Organization
          type: string
          default: 'cooktheryan'
        repoName:
          title: Repository Name
          type: string
          default: 'backstage-awx-resources'
    - title: AAP Project Defintion
      required:
        - description
        - name
        - repo
        - scm_type
        - organization
      properties:
        name:
          title: Name of the project
          type: string
          description: The name of the project
        description:
          title: Description
          type: string
          description: Description of the project
        scm_type:
          title: SCM for the project Assets
          type: string
          default: Git
          enum:
            - git
            - archive
          enumNames:
            - Git
            - Zip File
        repo:
          title: URL
          type: string
          description: The URL for the Git repository or archive
        organization:
          title: Organization
          type: string
          default: Default
          description: The organization for the project
    - title: Provide information about the CI method
      required:
        - ci
      properties:
        ci:
          title: Select a CI method
          type: string
          description: This action will create a simple CI based on chosen method
          default: ../../scaffolder-skeletons/github-actions-skeleton/
          enum:
            - ../../scaffolder-skeletons/github-actions-skeleton/
            - ../../scaffolder-skeletons/tekton-skeleton/
          enumNames:
            - GitHub Action
            - Tekton
  steps:
    - id: template
      name: Generating the source code component
      action: fetch:template
      input:
        url: ./skeleton
        values:
          repo: ${{ parameters.repo }}
          branch: ${{ parameters.branch }}
          name: ${{ parameters.name }}
          scm_type: ${{ parameters.scm_type }}
          organization: ${{ parameters.organization }}}
          description: ${{ parameters.description }}

    - id: publish
      name: Publishing to Source Code Repository
      action: publish:github:pull-request
      input:
        allowedHosts: ['github.com']
        description: ${{ parameters.description }}
        repoUrl: github.com?owner=${{ parameters.githubOrg }}&repo=${{ parameters.repoName }}
        defaultBranch: main

  output:
    links:
      - title: Source Code Repository
        url: ${{ steps.publish.output.remoteUrl }}
      - title: Open Component in catalog
        icon: catalog
        entityRef: ${{ steps.register.output.entityRef }}
