apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: python-template
  title: Python Golden Path Template
  description: Create a starter Python application managed by ArgoCD with GitHub Actions
  tags:
    - recommended
    - python
    - github-actions
    - argocd
spec:
  owner: user:janus-authors
  type: service

  parameters:
    - title: Provide the GitHub location
      required:
        - org
        - repo
      properties:
        org:
          title: AppCode
          type: string
          description: GitHub Organization
        repo:
          title: Repository
          type: string
          description: Repository name
    - title: Provide information about the new component
      required:
        - owner
      properties:
        description:
          title: Description
          type: string
          description: Help others understand what this component is for.
        owner:
          title: Owner
          type: string
          description: Owner of the component
          default: 'group: guest'
          ui:field: OwnerPicker
          ui:options:
            allowedKinds:
              - Group
    - title: Choose a CI method
      required:
        - ci
      properties:
        ci:
          title: Select a CI method
          type: string
          default: GitHub Actions
          enum:
            - ./github-actions-skeleton
            - ./manifests/base/tekton-pipeline.yaml
          enumNames:
            - GitHub Action
            - Tekton
    - title: Choose the image registry
      required:
        - registry
      properties:
        registry:
          title: Select a registry
          type: string
          default: image-registry.openshift-image-registry.svc:5000
          enum:
            - image-registry.openshift-image-registry.svc:5000
            - quay.io
          enumNames:
            - Internal OpenShift Registry
            - Quay
    - title: Generate OpenShift Route
      required:
        - route
      properties:
        route:
          title: Generate OpenShift Route
          type: boolean
          default: true
    - title: Provide information for Deployment with ArgoCD
      required:
        - namespace
      properties:
        namespace:
          title: Namespace
          type: string
          description: The namespace for deploying resources
        imagenamespace:
          title: Image Namespace
          type: string
          description: Enter the Image Namespace $REGISTRY/<IMAGE_NAMESPACE>/${{ parameters.repo }} for internal this will be the namespace
  steps:
    - id: template
      name: Generating CI Component
      action: fetch:template
      input:
        url: ${{ parameters.ci }}
        copyWithoutRender:
          - .github/workflows/

    - id: template
      name: Generating Component using quay.io
      if: ${{ parameters.registry === 'quay.io'}} && ${{ parameters.ci === './github-actions-skeleton'}}
      action: fetch:template
      input:
        url: ./skeleton
        copyWithoutRender:
          - .github/workflows/
        values:
          registry: ${{ parameters.registry }}
          component_id: ${{ parameters.repo }}
          description: ${{ parameters.description }}
          destination: ${{ parameters.org }}/${{ parameters.repo }}
          org: ${{ parameters.org }}
          owner: ${{ parameters.owner}}
          namespace: ${{ parameters.namespace }}
          imagenamespace: ${{ parameters.imagenamespace }}

    - id: template
      name: Generating Components using the OpenShift Registry
      # If the registry is the OpenShift Registry and tekton is selected
      if: ${{ parameters.registry === 'image-registry.openshift-image-registry.svc:5000'}} && ${{ parameters.ci === './manifests/base/tekton-pipeline.yaml'}}
      action: fetch:template
      input:  
        url: ./skeleton
        values:
          registry: ${{ parameters.registry }}
          component_id: ${{ parameters.repo }}
          description: ${{ parameters.description }}
          destination: ${{ parameters.org }}/${{ parameters.repo }}
          org: ${{ parameters.org }}
          owner: ${{ parameters.owner}}
          namespace: ${{ parameters.namespace }}
          imagenamespace: ${{ parameters.namespace }}

    - name: Delete Tekton Pipeline if GitHub Actions are selected
      if: ${{ parameters.ci === './github-actions-skeleton'}}
      action: fs:delete
      input:
        files:
          - ./manifests/base/tekton-pipeline.yaml
          - ./manifests/base/tekton-pipeline-run.yaml

    - name: Delete Route if not selected
      if: ${{ parameters.route === false}}
      action: fs:delete
      input:
        files:
          - ./manifests/base/route.yaml

    - id: publish
      name: Publishing to Source Code Repository
      action: publish:github
      input:
        allowedHosts: ["github.com"]
        description: ${{ parameters.description }}
        repoUrl: github.com?owner=${{ parameters.org }}&repo=${{ parameters.repo }}
        defaultBranch: main
    
    - id: register
      name: Registering the component
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps.publish.output.repoContentsUrl }}
        catalogInfoPath: "/catalog-info.yaml"

  output:
    links:
      - title: Source Code Repository
        url: ${{ steps.publish.output.remoteUrl }}
      - title: Open Component in catalog
        icon: catalog
        entityRef: ${{ steps.register.output.entityRef }}
